// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPcyuztA5RO1Qf5YeTPS47fQJaFCOH46A',
    appId: '1:624745750399:web:6d71a6c27edb1ccd09044a',
    messagingSenderId: '624745750399',
    projectId: 'clickcart-71df1',
    authDomain: 'clickcart-71df1.firebaseapp.com',
    storageBucket: 'clickcart-71df1.appspot.com',
    measurementId: 'G-89RXCBX3E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAGklBOFYA-e9CaIWg6AA_C9f88fuG00',
    appId: '1:624745750399:android:2b217905b472954509044a',
    messagingSenderId: '624745750399',
    projectId: 'clickcart-71df1',
    storageBucket: 'clickcart-71df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKDEruaQyrK85Bw2_Xim9XZm65po5ILW0',
    appId: '1:624745750399:ios:bfd9baf78478e1ad09044a',
    messagingSenderId: '624745750399',
    projectId: 'clickcart-71df1',
    storageBucket: 'clickcart-71df1.appspot.com',
    iosBundleId: 'com.example.clickcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKDEruaQyrK85Bw2_Xim9XZm65po5ILW0',
    appId: '1:624745750399:ios:da45dfb68a787d3f09044a',
    messagingSenderId: '624745750399',
    projectId: 'clickcart-71df1',
    storageBucket: 'clickcart-71df1.appspot.com',
    iosBundleId: 'com.example.clickcart.RunnerTests',
  );
}
